# Generated by Django 4.0.3 on 2022-04-05 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(max_length=5)),
                ('date_of_hire', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(choices=[('Greater Accra (GA)', 'Greater Accra (GA)'), ('Ashanti (AS)', 'Ashanti (AS)'), ('Brong East (BE)', 'Brong East (BE)'), ('Eastern Region (ER)', 'Eastern Region (ER)'), ('Volta Region (VR)', 'Volta Region (VR)'), ('Oti Region (OR)', 'Oti Region (OR)')], default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('end_date', models.DateField(auto_created=True)),
                ('date_signed', models.DateField(auto_created=True)),
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('actual_cost', models.CharField(blank=True, max_length=1000, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcs.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('end_date', models.DateField(auto_created=True)),
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcs.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(choices=[('Data Entry I', 'Data Entry I'), ('Data Entry II', 'Data Entry II'), ('Systems Analyst I', 'Systems Analyst I'), ('Systems Analyst II', 'Systems Analyst II'), ('Database Designer I', 'Database Designer I'), ('Database Designer II', 'Database Designer II'), ('Java I', 'Java I'), ('Java II', 'Java II'), ('C++ I', 'C++ I'), ('C++ II', 'C++ II'), ('Python I', 'Python I'), ('Python II', 'Python II'), ('ColdFusion I', 'ColdFusion I'), ('ColdFusion II', 'ColdFusion II'), ('ASP I', 'ASP I'), ('ASP II', 'ASP II'), ('Oracle DBA', 'Oracle DBA'), ('MS SQL Server', 'MS SQL Server'), ('DBA', 'DBA'), ('Network Engineer I', 'Network Engineer I'), ('Network Engineer II', 'Network Engineer II'), ('Web Administrator', 'Web Administrator'), ('Technical Writer', 'Technical Writer'), ('Project Manager', 'Project Manager')], max_length=200)),
                ('description', models.TextField()),
                ('rate_of_pay', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_hours', models.IntegerField()),
                ('bill_number', models.IntegerField()),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcs.projectassignment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcs.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSchedule',
            fields=[
                ('end_date', models.DateField(auto_created=True)),
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('Project_schedule', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('number_of_employees', models.IntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcs.project')),
                ('skills', models.ManyToManyField(to='bcs.skill')),
            ],
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project_schedule_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcs.projectschedule'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skill',
            field=models.ManyToManyField(to='bcs.skill'),
        ),
    ]
