# Generated by Django 4.0.3 on 2022-04-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectschedule',
            name='Project_schedule',
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bcs.employee'),
        ),
    ]
