# Generated by Django 4.0.3 on 2022-04-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0004_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='bcs.skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectschedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
