# Generated by Django 4.0.3 on 2022-04-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0005_remove_project_manager_project_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project',
        ),
    ]
