# Generated by Django 4.0.3 on 2022-04-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0006_remove_project_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(default='tsfsF', max_length=200),
            preserve_default=False,
        ),
    ]
