# Generated by Django 4.0.3 on 2022-04-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0007_remove_project_skills_project_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='skill',
            field=models.ManyToManyField(to='bcs.skill'),
        ),
    ]
