# Generated by Django 4.0.3 on 2022-04-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0008_projectassignment_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='skill',
        ),
    ]
